<html>
<head>
<title>Login</title>
</head>
<body>
	<h1>login</h1>
	<a
		href="https://www.facebook.com/dialog/oauth?client_id=2333204793575897&redirect_uri=https://localhost:8443/AccessFacebook/login-facebook">Login
		Facebook</a>
</body>
</html>